language: node_js

node_js:
  - stable
  - v0.12
  - v4
  - v5

sudo: false

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_install: export CXX="g++-4.8" CC="gcc-4.8"

before_script: npm link

script: npm run all
